name: CodeQL queries test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    name: Run CodeQL query tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: init
        uses: github/codeql-action/init@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Run tests
        run: |
          ${{ steps.init.outputs.codeql-path }} test run ./java/test/
